channel:
    common:
        poco: 
            package: com.netease.open.pocoservice
    qq:
        uat:
            package: com.qq.app.v2
            bundle_id: com.qq.app.v2
        stage:
            package: com.qq.app.v2
            bundle_id: com.qq.app.v2
        prod:
            package: com.qq.app.v2
            bundle_id: com.qq.app.v2