Phone_conf:
    MI8_3:
        platformName: Android
        udid: a306cde
    
    OPPO_6:
        platformName: Android
        udid: 97f1303d

    OPPO_7:
        platformName: Android
        udid: c442015
    
    HUAWEI_9:
        platformName: Android
        udid: UFRBB18A16500162
    
    MEIZU_10:
        platformName: Android
        udid: 79BQADRQ6CGWD
    
    N6_PRO_13:
        platformName: Android
        udid: f312c82f
    
    NUBIA_15:
        platformName: Android
        udid: ad1bd99a
    
    OPPO_17:
        platformName: Android
        udid: d730d16b

    OPPO_18:
        platformName: Android
        udid: 186d9ead
    
    REDMI_19:
        platformName: Android
        udid: 134b3e89
        
    IQOO_20:
        platformName: Android
        udid: 14a2f559
    
    HUAWEI_21:
        platformName: Android
        udid: ADFDU20525005854
    
    VIVO_22:
        platformName: Android
        udid: 2a4c79ae
    
    MI10_23:
        platformName: Android
        udid: c29066e7
    
    HUAWEI_24:
        platformName: Android
        udid: 8KE0220210018657
    
    HUAWEI_25:
        platformName: Android
        udid: 5VSNW19517003630

    HUAWEI_26:
        platformName: Android
        udid: 9YS0220218000476

    MI9_27:
        platformName: Android
        udid: bc79a99e
        
    VIVO_28:
        platformName: Android
        udid: 2c5c9ee7

    OPPO_29:
        platformName: Android
        udid: f130295
    
    OPPO_30:
        platformName: Android
        udid: 3ab12fd

    Pixel5_31:
        platformName: Android
        udid: 09131FDD40023T

    REDMI_45:
        platformName: Android
        udid: 86208c29
        
    REALME_46:
        platformName: Android
        udid: d6a54db9
        
    IQOO_47:
        platformName: Android
        udid: 1576457605007R5
        
    HONOR_48:
        platformName: Android
        udid: AKRSVB1731008616
    
    VIVO_49:
        platformName: Android
        udid: 1562219263000XJ

    OPPO_50:
        platformName: Android
        udid: YLE64LRS49ZLWCKN

    SAMSUNG_51:
        platformName: Android
        udid: R5CRC0399CD    

    SAMSUNG_52:
        platformName: Android
        udid: R5CR217YH6L

    HUAWEI_53:
        platformName: Android
        udid: THF6R20513001544

    HONOR_54:
        platformName: Android
        udid: ERLDU19723003688
    
    POCO_55:
        platformName: Android
        udid: da122be0

    POCO_56:
        platformName: Android
        udid: 73ce00b2469c
    
    VIVO_57:
        platformName: Android
        udid: 10AC4S1E6S000UZ

    INFINIX_58:
        platformName: Android
        udid: 0798431271073248
    
    VIVO_60:
        platformName: Android
        udid: 1392839102000CK
    
    POCO_67:
        platformName: Android
        udid: 9HMZRGFUBASGQWGQ
    
    VIVO_74:
        platformName: Android
        udid: K7YLW8LBZDBISSAA

    OPPO_75:
        platformName: Android
        udid: bc50696d

    MI13_79:
        platformName: Android
        udid: 349b04c9

    SAMSUNG_80:
        platformName: Android
        udid: RFCW70VZFWJ

    REALME_81:
        platformName: Android
        udid: V8SWHQVOF6IBNJ49
        
        
    #新ios規範
    IPHONEXR_38:
        platformName: iOS
        udid: 00008020-001979290168002E
        port: 8301
        model: XR
        
    IPHONE12mini_41:
        platformName: iOS
        udid: 00008101-0012116401E0001E
        port: 8302
        model: 12MINI

    IPHONEX:
        platformName: iOS
        udid: d4167be885e65b4528c770e5040dc621d853409e
        port: 8301
        model: X

    IPHONE7_1:
        platformName: iOS
        udid: 2e0b0115946b98168d9ff5ca74ff9b45a87f6ac1
        port: 8302
        model: 7

    IPHONE7_2:
        platformName: iOS
        udid: c8becbdad1e1d9f10f6d7b9352e0340a4af7a6f6
        port: 8303
        model: 7